[package]
edition = "2021"
license = "MIT"
name = "msrv"
publish = []
rust-version = "1.72.0"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
