name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cargo-bins/cargo-binstall@main
    - name: XTask install
      run: cargo xt ensure-installed
    - name: XTask CI
      run: cargo xt ci
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
